spring:
  datasource:
    url: jdbc:h2:mem:prod_db
    driverClassName: org.h2.Driver
    username: admin
    password: admin@123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform  # Optional: suppresses JTA log warning

server:
  port: 8081
